CRIAR CRUD DE USUARIOS:

1. CRIAR A PASTA Usuarios dentro de Pages
2. CRIAR O COMPONENTE UsuariosIndex.jsx
3. CRIAR O COMPONENTE UsuariosForm.jsx

4. CRIAR AS ROTAS PARA USUARIOS DENTRO DO routes/AppRoutes.jsx
5. CRIAR NO MENU O LINK USUARIOS

6. SIGA COMO MODELO OS ARQUIVOS DO CRUD DE CATEGORIAS.
OBS: FAÇA DETALHADAMENTE E COM CUIDADO CADA CÓDIGO.
VOCÊ DEVE FAZER E TESTAR PARA VER SE NÃO HÁ ERROS.
